import { OrderType } from "../../backend/src/order/types/enums/type.enum";
import { OrderPriority } from "../../backend/src/order/types/enums/priority.enum";
import { OrderStatus } from "../../backend/src/order/types/enums/status.enum";
import { PaymentMethod } from "../../backend/src/order/types/enums/payment-method.enum";
import { ItemCategory } from "../../backend/src/order/types/enums/item-category.enum";
import type { Order } from "../../backend/src/order/order.schema";

export const ordersMock: Order[] = [
  {
    priority: OrderPriority.NORMAL,
    number: 1001,
    status: OrderStatus.DELIVERED,
    ordered: new Date("2026-02-01T12:30:00"),
    items: [
      {
        itemId: "1",
        itemName: "Hambúrguer Clássico",
        category: ItemCategory.FOOD,
        quantity: 2,
        ingredients: ["pão", "carne", "queijo", "alface", "tomate"],
        unitPrice: 35.0,
        observation: ["sem cebola"],
      },
      {
        itemId: "2",
        itemName: "Refrigerante",
        category: ItemCategory.DRINK,
        quantity: 2,
        ingredients: ["gelo"],
        unitPrice: 8.0,
      },
    ],
    type: OrderType.TABLE,
    tableNumber: 5,
    waiterId: "w001",
    waiterName: "João Silva",
    transactionHandlerId: "w001",
    transactionHandlerName: "João Silva",
    subtotal: 86.0,
    discount: 5.0,
    deliveryFee: 0,
    total: 81.0,
    amountPaid: 100.0,
    change: 19.0,
    paymentMethod: PaymentMethod.CASH,
    isPaid: true,
    startedPreparing: new Date("2026-02-01T12:35:00"),
    finishedPreparing: new Date("2026-02-01T12:50:00"),
    _id: "order_001",
    createdAt: new Date("2026-02-01T12:30:00"),
    updatedAt: new Date("2026-02-01T13:00:00"),
  } as any,
  {
    priority: OrderPriority.HIGH,
    number: 1002,
    status: OrderStatus.PREPARING,
    ordered: new Date("2026-02-01T13:15:00"),
    items: [
      {
        itemId: "3",
        itemName: "Pizza Margherita",
        category: ItemCategory.FOOD,
        quantity: 1,
        ingredients: ["massa", "molho", "queijo", "tomate", "manjericão"],
        unitPrice: 45.0,
      },
      {
        itemId: "4",
        itemName: "Cerveja",
        category: ItemCategory.DRINK,
        quantity: 2,
        ingredients: [],
        unitPrice: 12.0,
      },
    ],
    type: OrderType.TABLE,
    tableNumber: 3,
    waiterId: "w002",
    waiterName: "Maria Santos",
    subtotal: 69.0,
    discount: 0,
    deliveryFee: 0,
    total: 69.0,
    amountPaid: 0,
    change: 0,
    paymentMethod: PaymentMethod.CREDIT_CARD,
    isPaid: false,
    startedPreparing: new Date("2026-02-01T13:20:00"),
    _id: "order_002",
    createdAt: new Date("2026-02-01T13:15:00"),
    updatedAt: new Date("2026-02-01T13:20:00"),
  } as any,
  {
    priority: OrderPriority.NORMAL,
    number: 1003,
    status: OrderStatus.PENDING,
    ordered: new Date("2026-02-01T14:00:00"),
    items: [
      {
        itemId: "5",
        itemName: "Salada Caesar",
        category: ItemCategory.FOOD,
        quantity: 1,
        ingredients: ["alface", "crouton", "parmesão", "molho caesar"],
        unitPrice: 38.0,
        observation: ["tempero na lateral"],
      },
      {
        itemId: "6",
        itemName: "Água",
        category: ItemCategory.DRINK,
        quantity: 1,
        ingredients: [],
        unitPrice: 5.0,
      },
    ],
    type: OrderType.BALCONY,
    waiterId: "w001",
    waiterName: "João Silva",
    subtotal: 43.0,
    discount: 0,
    deliveryFee: 0,
    total: 43.0,
    amountPaid: 0,
    change: 0,
    paymentMethod: PaymentMethod.PIX,
    isPaid: false,
    _id: "order_003",
    createdAt: new Date("2026-02-01T14:00:00"),
    updatedAt: new Date("2026-02-01T14:00:00"),
  } as any,
  {
    priority: OrderPriority.NORMAL,
    number: 1004,
    status: OrderStatus.DELIVERED,
    ordered: new Date("2026-02-01T14:30:00"),
    items: [
      {
        itemId: "7",
        itemName: "Marmita Executiva",
        category: ItemCategory.FOOD,
        quantity: 1,
        ingredients: ["arroz", "feijão", "frango", "brócolis", "batata"],
        unitPrice: 42.0,
      },
      {
        itemId: "8",
        itemName: "Suco Natural",
        category: ItemCategory.DRINK,
        quantity: 1,
        ingredients: ["laranja", "gelo"],
        unitPrice: 10.0,
      },
    ],
    type: OrderType.DELIVERY,
    address: {
      cep: 1310100,
      street: "Avenida Paulista",
      number: "1000",
      neighborhood: "Bela Vista",
      city: "São Paulo",
      complement: "Apto 1205",
    },
    waiterId: "w003",
    waiterName: "Carlos Oliveira",
    transactionHandlerId: "w003",
    transactionHandlerName: "Carlos Oliveira",
    subtotal: 52.0,
    discount: 0,
    deliveryFee: 10.0,
    total: 62.0,
    amountPaid: 62.0,
    change: 0,
    paymentMethod: PaymentMethod.PIX,
    isPaid: true,
    startedPreparing: new Date("2026-02-01T14:35:00"),
    finishedPreparing: new Date("2026-02-01T14:55:00"),
    _id: "order_004",
    createdAt: new Date("2026-02-01T14:30:00"),
    updatedAt: new Date("2026-02-01T15:10:00"),
  } as any,
  {
    priority: OrderPriority.HIGH,
    number: 1005,
    status: OrderStatus.DONE,
    ordered: new Date("2026-02-01T15:00:00"),
    items: [
      {
        itemId: "9",
        itemName: "Steak Premium",
        category: ItemCategory.FOOD,
        quantity: 1,
        ingredients: ["carne 300g", "batata", "legumes"],
        unitPrice: 85.0,
        observation: ["mal passado"],
      },
      {
        itemId: "10",
        itemName: "Vinho Tinto",
        category: ItemCategory.DRINK,
        quantity: 1,
        ingredients: [],
        unitPrice: 60.0,
      },
    ],
    type: OrderType.TABLE,
    tableNumber: 1,
    waiterId: "w002",
    waiterName: "Maria Santos",
    subtotal: 145.0,
    discount: 10.0,
    deliveryFee: 0,
    total: 135.0,
    amountPaid: 0,
    change: 0,
    paymentMethod: PaymentMethod.CREDIT_CARD,
    isPaid: false,
    startedPreparing: new Date("2026-02-01T15:05:00"),
    finishedPreparing: new Date("2026-02-01T15:30:00"),
    _id: "order_005",
    createdAt: new Date("2026-02-01T15:00:00"),
    updatedAt: new Date("2026-02-01T15:30:00"),
  } as any,
  {
    priority: OrderPriority.NORMAL,
    number: 1006,
    status: OrderStatus.CANCELED,
    cancellationReason: "Cliente desistiu do pedido",
    ordered: new Date("2026-02-01T15:20:00"),
    items: [
      {
        itemId: "11",
        itemName: "Açaí",
        category: ItemCategory.DESSERT,
        quantity: 2,
        ingredients: ["açaí", "granola", "banana", "mel"],
        unitPrice: 25.0,
      },
    ],
    type: OrderType.TAKEAWAY,
    waiterId: "w001",
    waiterName: "João Silva",
    subtotal: 50.0,
    discount: 0,
    deliveryFee: 0,
    total: 50.0,
    amountPaid: 0,
    change: 0,
    paymentMethod: PaymentMethod.DEBIT_CARD,
    isPaid: false,
    _id: "order_006",
    createdAt: new Date("2026-02-01T15:20:00"),
    updatedAt: new Date("2026-02-01T15:25:00"),
  } as any,
  {
    priority: OrderPriority.NORMAL,
    number: 1007,
    status: OrderStatus.DELIVERED,
    ordered: new Date("2026-02-01T15:45:00"),
    items: [
      {
        itemId: "12",
        itemName: "Pastel",
        category: ItemCategory.FOOD,
        quantity: 4,
        ingredients: ["massa", "carne", "queijo"],
        unitPrice: 6.0,
      },
      {
        itemId: "13",
        itemName: "Café",
        category: ItemCategory.DRINK,
        quantity: 2,
        ingredients: ["leite"],
        unitPrice: 5.0,
      },
    ],
    type: OrderType.BALCONY,
    waiterId: "w003",
    waiterName: "Carlos Oliveira",
    transactionHandlerId: "w003",
    transactionHandlerName: "Carlos Oliveira",
    subtotal: 34.0,
    discount: 0,
    deliveryFee: 0,
    total: 34.0,
    amountPaid: 50.0,
    change: 16.0,
    paymentMethod: PaymentMethod.CASH,
    isPaid: true,
    startedPreparing: new Date("2026-02-01T15:47:00"),
    finishedPreparing: new Date("2026-02-01T15:55:00"),
    _id: "order_007",
    createdAt: new Date("2026-02-01T15:45:00"),
    updatedAt: new Date("2026-02-01T16:00:00"),
  } as any,
  {
    priority: OrderPriority.HIGH,
    number: 1008,
    status: OrderStatus.PREPARING,
    ordered: new Date("2026-02-01T16:10:00"),
    items: [
      {
        itemId: "14",
        itemName: "Parmegiana de Carne",
        category: ItemCategory.FOOD,
        quantity: 1,
        ingredients: ["carne", "molho", "queijo", "macarrão"],
        unitPrice: 55.0,
      },
      {
        itemId: "15",
        itemName: "Refrigerante Lata",
        category: ItemCategory.DRINK,
        quantity: 2,
        ingredients: [],
        unitPrice: 7.0,
      },
    ],
    type: OrderType.DELIVERY,
    address: {
      cep: 1220000,
      street: "Rua Augusta",
      number: "500",
      neighborhood: "Centro",
      city: "São Paulo",
    },
    waiterId: "w002",
    waiterName: "Maria Santos",
    subtotal: 69.0,
    discount: 0,
    deliveryFee: 12.0,
    total: 81.0,
    amountPaid: 0,
    change: 0,
    paymentMethod: PaymentMethod.PIX,
    isPaid: false,
    startedPreparing: new Date("2026-02-01T16:15:00"),
    _id: "order_008",
    createdAt: new Date("2026-02-01T16:10:00"),
    updatedAt: new Date("2026-02-01T16:15:00"),
  } as any,
  {
    priority: OrderPriority.NORMAL,
    number: 1009,
    status: OrderStatus.DONE,
    ordered: new Date("2026-02-01T16:30:00"),
    items: [
      {
        itemId: "16",
        itemName: "Frango à Parmegiana",
        category: ItemCategory.FOOD,
        quantity: 2,
        ingredients: ["frango", "queijo", "molho tomate", "arroz"],
        unitPrice: 48.0,
      },
    ],
    type: OrderType.TABLE,
    tableNumber: 8,
    waiterId: "w001",
    waiterName: "João Silva",
    subtotal: 96.0,
    discount: 0,
    deliveryFee: 0,
    total: 96.0,
    amountPaid: 0,
    change: 0,
    paymentMethod: PaymentMethod.DEBIT_CARD,
    isPaid: false,
    startedPreparing: new Date("2026-02-01T16:35:00"),
    finishedPreparing: new Date("2026-02-01T16:55:00"),
    _id: "order_009",
    createdAt: new Date("2026-02-01T16:30:00"),
    updatedAt: new Date("2026-02-01T16:55:00"),
  } as any,
  {
    priority: OrderPriority.NORMAL,
    number: 1010,
    status: OrderStatus.PENDING,
    ordered: new Date("2026-02-01T17:00:00"),
    items: [
      {
        itemId: "17",
        itemName: "Brownie",
        category: ItemCategory.DESSERT,
        quantity: 3,
        ingredients: ["chocolate", "trigo", "ovos", "manteiga"],
        unitPrice: 15.0,
        observation: ["morno"],
      },
      {
        itemId: "18",
        itemName: "Cappuccino",
        category: ItemCategory.DRINK,
        quantity: 3,
        ingredients: ["café", "leite", "chocolate em pó"],
        unitPrice: 12.0,
      },
    ],
    type: OrderType.BALCONY,
    waiterId: "w003",
    waiterName: "Carlos Oliveira",
    subtotal: 81.0,
    discount: 0,
    deliveryFee: 0,
    total: 81.0,
    amountPaid: 0,
    change: 0,
    paymentMethod: PaymentMethod.CASH,
    isPaid: false,
    _id: "order_010",
    createdAt: new Date("2026-02-01T17:00:00"),
    updatedAt: new Date("2026-02-01T17:00:00"),
  } as any,
];
